#!/usr/bin/env python3
"""Write clues into the page from a JSON file, keyed by answer rather than by number.

Keying by answer on the way in matters. Clue numbers move with the block pattern, so a
file of `"34A": "..."` silently rots the moment the grid changes, and the rot is
invisible: every clue still renders, just against the wrong entry. Alpha's list would
have collided with 41 of beta's numbers that way. Keyed by answer, a stale clue is
reported as an answer that is no longer in the grid.

The eight gift clues carry over from alpha untouched, because the answers are identical
and only their numbers moved.

Usage:
  clues.py --page ../../public/ataliena/puzzle-beta.html --clues beta-clues.json
  clues.py --page ... --clues ... --report     # what is written, what is missing
"""
import argparse
import base64
import json
import re
import sys

from grid import N, entries, is_block


def rot13(s):
    return "".join(chr((ord(c) - 52) % 26 + 65) if "A" <= c <= "Z" else c for c in s)


def grid_from_page(path):
    src = open(path, encoding="utf-8").read()
    layout = re.search(r'const LAYOUT="([^"]*)"', src).group(1)
    enc = re.search(r'const SOL_ENC="([^"]*)"', src).group(1)
    sol = rot13(base64.b64decode(enc).decode())
    letters, k = [], 0
    for i in range(N * N):
        if is_block(layout, i):
            letters.append(None)
        else:
            letters.append(sol[k])
            k += 1
    return src, layout, letters


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--page", required=True)
    ap.add_argument("--clues", required=True)
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    src, layout, letters = grid_from_page(args.page)
    by_answer = json.load(open(args.clues))
    ents = entries(layout)
    answers = {"".join(letters[i] for i in e["cells"]): e["key"] for e in ents}

    stale = [a for a in by_answer if a not in answers]
    unclued = [(answers[a], a) for a in answers if a not in by_answer]

    print(f"{len(answers)} entries, {len(by_answer) - len(stale)} clued, "
          f"{len(unclued)} to write, {len(stale)} stale")
    if stale:
        print("stale (answer not in this grid): " + ", ".join(sorted(stale)))
    if unclued:
        print("unclued: " + ", ".join(f"{k} {a}" for k, a in sorted(unclued, key=lambda r: -len(r[1]))))
    if args.report:
        return 0

    # Keyed by number on the way out, which is what the page reads.
    out = {}
    for answer, key in answers.items():
        if answer in by_answer:
            out[key] = by_answer[answer]
    ordered = sorted(out, key=lambda k: (k[-1] != "A", int(k[:-1])))
    body = "\n".join(f'  "{k}": {json.dumps(out[k], ensure_ascii=False)},' for k in ordered)
    block = ("const CLUES = {\n"
             "  /* Generated by clues.py from a file keyed by answer, not by number.\n"
             "     Do not hand-edit: clue numbers move with the block pattern, and a\n"
             "     stale number shows a real-looking clue on the wrong entry. */\n"
             f"{body}\n}};")
    new = re.sub(r"const CLUES = \{.*?\n\};", lambda _m: block, src, flags=re.S)
    if new == src:
        raise SystemExit("could not find the CLUES block to replace")
    open(args.page, "w", encoding="utf-8").write(new)
    print(f"wrote {len(out)} clues into {args.page}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
